In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape

(5,)

In [5]:
# 2차원 List
data2 = [
        [1,2,3,4],
        [5,6,7,8]
        ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
# numpy 로 2차원 배열로 변경하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# 2행 4열 : 4차원 데이터
arr2.shape

(2, 4)

In [8]:
# 0으로 구성 된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
# 3 : page임. 페이지 
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
# 1로만 구성된 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# 숫자 8로 구성된 3행 5열 배열 생성
np.full((3,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [16]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr1.dtype

dtype('float64')

In [19]:
arr3 = np.array([1,2,3,4,5], dtype=np.int64)
arr3.dtype

dtype('int64')

In [20]:
# data type을 변견
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [21]:
float_arr1

array([1., 2., 3., 4., 5.])

In [35]:
# 연산
# 대괄호 말고 괄호 두개(튜플)써도 됨
arr1 = np.array((
  [1,2,3],
  [ 4,5,6]
), dtype=np.float64)

arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
arr2 = np.array((
  [7,8,9],
  [10,11,12]
), dtype=np.float64)

arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [37]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [38]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [39]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [40]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [41]:
arr3 = 1/ arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5]

5

In [44]:
arr[5:9]

array([5, 6, 7, 8])

In [46]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [47]:
arr[:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[8:]

array([12,  9])

# 2차원 배열

In [49]:
arr2d = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]

])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
arr2d.dtype

dtype('int64')

In [54]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [58]:
# 1에서 2번행의 자료 출력
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [60]:
# 0,1 열의 차료 출력
arr2d[:,[0,1]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [61]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [62]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
arr2d[0:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수 발생
- rand : 0부터 1사이의 균일 분포
- randn : 가우시안 표준 정규 분포
- randint : 균일 분포의 정수 난수

# Boolean Indexing

In [105]:
names = np.array(["Charles", "Kenny","Hayoung","Charles","Hayoung","Kenny","Kenny"])
data = np.random.randn(7, 4)

In [106]:
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [107]:
names.shape

(7,)

In [108]:
data

array([[-0.95286187, -0.28130823, -0.13303621,  1.23454107],
       [ 0.26384001,  1.08726352, -1.96287663, -0.49783651],
       [ 1.3885137 , -1.77572752,  0.38748799,  0.11561316],
       [-0.7485684 , -0.05311083, -0.16707167,  0.2125689 ],
       [ 0.21680854, -2.23110581, -0.85352528,  0.31079449],
       [-0.53482246, -0.1829686 , -0.4291819 , -0.9944195 ],
       [ 0.07355472, -0.34822443, -0.099195  ,  1.36279158]])

In [109]:
data.shape

(7, 4)

In [110]:
# Mask를 이용한 추출
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [111]:
# TRUE 값에 해당하는 행과열
data[names == "Charles", :]

array([[-0.95286187, -0.28130823, -0.13303621,  1.23454107],
       [-0.7485684 , -0.05311083, -0.16707167,  0.2125689 ]])

In [112]:
data[(names == "Carles") | (names == "Kenny"), :]

array([[ 0.26384001,  1.08726352, -1.96287663, -0.49783651],
       [-0.53482246, -0.1829686 , -0.4291819 , -0.9944195 ],
       [ 0.07355472, -0.34822443, -0.099195  ,  1.36279158]])

In [113]:
data[:]

array([[-0.95286187, -0.28130823, -0.13303621,  1.23454107],
       [ 0.26384001,  1.08726352, -1.96287663, -0.49783651],
       [ 1.3885137 , -1.77572752,  0.38748799,  0.11561316],
       [-0.7485684 , -0.05311083, -0.16707167,  0.2125689 ],
       [ 0.21680854, -2.23110581, -0.85352528,  0.31079449],
       [-0.53482246, -0.1829686 , -0.4291819 , -0.9944195 ],
       [ 0.07355472, -0.34822443, -0.099195  ,  1.36279158]])

In [114]:
data[:, 3]

array([ 1.23454107, -0.49783651,  0.11561316,  0.2125689 ,  0.31079449,
       -0.9944195 ,  1.36279158])

In [115]:
# data의 4번쨰 열 값중 0보다 작은 것의 mask 만들기

data[data[:, 3] < 0, :]

array([[ 0.26384001,  1.08726352, -1.96287663, -0.49783651],
       [-0.53482246, -0.1829686 , -0.4291819 , -0.9944195 ]])

In [116]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
data[data[:, 3] < 0, :] = 0
data

array([[-0.95286187, -0.28130823, -0.13303621,  1.23454107],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.3885137 , -1.77572752,  0.38748799,  0.11561316],
       [-0.7485684 , -0.05311083, -0.16707167,  0.2125689 ],
       [ 0.21680854, -2.23110581, -0.85352528,  0.31079449],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.07355472, -0.34822443, -0.099195  ,  1.36279158]])

In [117]:
# 정렬
arr = np.random.rand(8)
arr

array([0.1620049 , 0.97456672, 0.15538527, 0.68968313, 0.18739424,
       0.46293291, 0.57499145, 0.57853311])

In [118]:
# 오름차순 정렬
np.sort(arr)

array([0.15538527, 0.1620049 , 0.18739424, 0.46293291, 0.57499145,
       0.57853311, 0.68968313, 0.97456672])

In [119]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.97456672, 0.68968313, 0.57853311, 0.57499145, 0.46293291,
       0.18739424, 0.1620049 , 0.15538527])

In [121]:
arr = np.random.rand(5,3)
arr

array([[0.52745474, 0.96324361, 0.32489549],
       [0.14092817, 0.65247827, 0.97850618],
       [0.33221463, 0.42496227, 0.91051446],
       [0.50958872, 0.52661438, 0.29023912],
       [0.64696156, 0.48644025, 0.87874625]])

In [122]:
np.sort(arr, axis=0) # 0 : 열방향

array([[0.14092817, 0.42496227, 0.29023912],
       [0.33221463, 0.48644025, 0.32489549],
       [0.50958872, 0.52661438, 0.87874625],
       [0.52745474, 0.65247827, 0.91051446],
       [0.64696156, 0.96324361, 0.97850618]])

In [123]:
np.sort(arr, axis=1) # 1 : 행방향


array([[0.32489549, 0.52745474, 0.96324361],
       [0.14092817, 0.65247827, 0.97850618],
       [0.33221463, 0.42496227, 0.91051446],
       [0.29023912, 0.50958872, 0.52661438],
       [0.48644025, 0.64696156, 0.87874625]])

In [125]:
# 내림차순
np.sort(arr, axis=1)[:,::-1]

array([[0.96324361, 0.52745474, 0.32489549],
       [0.97850618, 0.65247827, 0.14092817],
       [0.91051446, 0.42496227, 0.33221463],
       [0.52661438, 0.50958872, 0.29023912],
       [0.87874625, 0.64696156, 0.48644025]])

In [126]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape

In [136]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
# 행 8 개 있음
arr.shape

(8,)

In [138]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [139]:
# 3차원 배열로 변경
arr2 = np.reshape(arr,(2,2,2)) # (page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [140]:
# 2차원 배열을 1차원으로 변경
# -1 데이터의 갯수를 정할수 없을때 씀
arr3 = arr1.reshape(-1,1)
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [143]:
arr4 = arr2.reshape(-1)
# -1 : 행의 수를 알아서 지정해라 
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])