In [1]:
# GPU 사용 설정
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = '1'

In [2]:
import pandas as pd
data= pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

- admit : 1합격,0불합격
- gre : 영어 성적
- gpa : 학점
- rank : 지원한 대학원 수준

### Preprocessing(전처리)

In [3]:
# 결측치 확인
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [4]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터를 다른값으로 대체
# data.fillna(100)

In [5]:
# 결측치 확인
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [6]:
# rank의 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [7]:
# 영어 점수의 최소값과 최대값
print("최대값 :",data['gre'].max())
print("최소값 :",data['gre'].min())

최대값 : 800.0
최소값 : 220.0


In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 425 entries, 0 to 425
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   admit   425 non-null    int64  
 1   gre     425 non-null    float64
 2   gpa     425 non-null    float64
 3   rank    425 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 16.6 KB


In [9]:
# Training Data
x = data[['gre', 'gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [10]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [11]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

> 입력층 3개. 출력은 1개

---
## Deep Learning Model 만들기

In [12]:
from tensorflow import keras

In [13]:
# 입력레이어를 주는데 층은 아니다?
input_layer = keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256, activation='tanh')
output_layer = keras.layers.Dense(1, activation='sigmoid')

In [14]:
model = keras.Sequential(
    [input_layer,
    hidden_layer,
    output_layer]
)

Optimizer => Learning rate를 알맞게 조정해줌 ->(y - y^)
- adam
- adagrad
- adadelta
- rmsprop
- sgd  

loss : 손실함수
- binary_crossentropy : 분류 및 확률 예측 함수

metrics : 모델의 평가 기준


In [15]:
# 손실함수
model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [16]:
# 학습 시키기
# 일반적인 fit은 못씀 pandas에 들어있어서 -> numpy로 바꿔줘야해
import numpy as np
model.fit(np.array(x), np.array(y), epochs=500)

Epoch 1/500
14/14 [==============================] - 1s 1ms/step - loss: 0.7388 - accuracy: 0.5412
Epoch 2/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6850 - accuracy: 0.5600
Epoch 3/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6852 - accuracy: 0.5412
Epoch 4/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6657 - accuracy: 0.5882
Epoch 5/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6731 - accuracy: 0.5553
Epoch 6/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6883 - accuracy: 0.5482
Epoch 7/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6765 - accuracy: 0.5647
Epoch 8/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6569 - accuracy: 0.6047
Epoch 9/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6592 - accuracy: 0.6071
Epoch 10/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6683 - accuracy: 0.5741
Epoch 11/

In [17]:
# hidden layer 가중치 값 출력
# 히든레이어에 AF를 주지 않으면 이값이 그대로 넘어감
hidden_layer.get_weights()[0]

array([[ 1.28198499e-02, -1.49054497e-01, -1.50191635e-01,
        -4.36237231e-02,  1.44554079e-01, -5.55974245e-02,
         1.01302415e-01, -1.05034262e-01,  8.14167857e-02,
         7.28662610e-02, -3.73200886e-03, -3.70143279e-02,
         1.47312224e-01,  1.51245505e-01,  8.28421563e-02,
         8.61184001e-02, -1.01483785e-01,  4.45457697e-02,
         9.91608799e-02,  3.01360525e-02,  1.13430023e-01,
        -4.26849052e-02, -7.06035122e-02, -9.18546319e-02,
         3.43616935e-03,  1.13041490e-01, -6.20169938e-02,
        -1.47826076e-01, -8.24208856e-02,  8.31949115e-02,
         1.81579180e-02,  9.30495709e-02, -5.72316274e-02,
        -1.08880237e-01, -4.16009054e-02,  1.19151115e-01,
        -1.30485911e-02,  6.56986833e-02,  3.78043726e-02,
        -3.37882824e-02, -1.00254886e-01,  1.33033276e-01,
        -1.07340671e-01, -5.42677119e-02, -9.02752951e-02,
        -7.30568171e-02,  1.37846410e-01,  1.27555698e-01,
         1.06074423e-01, -1.34382874e-01,  1.15919948e-0

In [18]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [19]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[ 0.99999255, -1.        , -1.        , ...,  1.        ,
        -1.        ,  1.        ],
       [ 1.        , -1.        , -1.        , ...,  1.        ,
        -1.        ,  1.        ],
       [ 1.        , -1.        , -1.        , ...,  1.        ,
        -1.        ,  1.        ],
       ...,
       [ 0.9999994 , -1.        , -1.        , ...,  1.        ,
        -1.        ,  1.        ],
       [ 1.        , -1.        , -1.        , ...,  1.        ,
        -1.        ,  1.        ],
       [ 1.        , -1.        , -1.        , ...,  1.        ,
        -1.        ,  1.        ]], dtype=float32)>